apiVersion: v1
kind: Service
metadata:
  name: tmdb-proxy-service
  labels:
    app: tmdb-proxy
spec:
  selector:
    app: tmdb-proxy
  ports:
    - protocol: TCP
      port: 9000 
      targetPort: 9000 
  type: ClusterIP 
