services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - streamtrack

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - streamtrack
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import

  tmdb-proxy:
    build: ./tmdb-proxy
    container_name: tmdb-proxy
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - streamtrack

  api:
    build: ./api
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - streamtrack
    depends_on:
      - mongo
      - keycloak
    restart: always
    
volumes:
  keycloak_data:
  mongo_data:

networks:
  streamtrack:
    driver: bridge
