apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "frontend"
  NEXT_PUBLIC_KEYCLOAK_REALM: "streamtrack"
  NEXT_PUBLIC_KEYCLOAK_URL: "http://localhost"
  NEXT_PUBLIC_API_URL: "http://localhost/api"
  NEXT_PUBLIC_TMDB_PROXY_URL: "http://localhost/tmdb"

  KEYCLOAK_URL: "http://keycloak-service:8080"
  API_URL: "http://api-service:8000"
  TMDB_PROXY_URL: "http://tmdb-proxy-service:9000"
