apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-static-pvc
  labels:
    app: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard