apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  keycloak_server_url: "http://keycloak-service:8080" 
  keycloak_realm: "streamtrack" 
  keycloak_client_id: "frontend"
  keycloak_audience: "account"
  keycloak_issuer: "http://localhost/realms/streamtrack"